on:
  workflow_dispatch:
  push:
    branches: ["uat"]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: "Login via Azure CLI"
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.azure_credentials }}
      - name: "Login ACR"
        uses: azure/docker-login@v2
        with: 
          login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and push image
        id: build-image
        run: |
          docker build . -t ${{ vars.REGISTRY_LOGIN_SERVER }}/regnimosssba/karma-mail:latest -f "Dockerfile" 
          docker push ${{ vars.REGISTRY_LOGIN_SERVER }}/regnimosssba/karma-mail:latest