name: Build and Deploy UAT
on:
  workflow_dispatch:
  push:
    branches: ["uat"]
jobs:
  publish_image:
    runs-on: ubuntu-latest
    environment: vaughan-nelson-uat
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build and push image
      id: build-image
      run: |
        az acr build --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/karma-mail:latest --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file "Dockerfile" .
    # docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/karma-mail:${{ github.sha }}
    # docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/karma-mail:${{ github.sha }}
